# Generated by Django 5.0.7 on 2024-07-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPurchase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SalesEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('phonepe_upi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_pmt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zomato', models.DecimalField(decimal_places=2, max_digits=10)),
                ('swiggy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bms', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expenditure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_sale', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StockRequisition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('item_type', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=10)),
                ('closing', models.FloatField()),
                ('required', models.FloatField()),
                ('delivered', models.FloatField()),
            ],
        ),
    ]
