# Generated by Django 5.0.7 on 2024-08-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_alter_dailypurchase_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrequisition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stockrequisition',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stockrequisition',
            name='item_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stockrequisition',
            name='unit',
            field=models.CharField(max_length=50),
        ),
    ]
